### ISSUE TITLE
Ability to check container status from within project

### ISSUE THREAD

**Issue by donaldwasserman** [zak-schlemmer/robot#21]
Add ability to do `robot status` like `robot sync status` within a robot project folder.

**Comment by zak-schlemmer** [comment]
I assumed the `robot list` functionality would be used for this.
What other aspects would you like to see for this?
Just information about that specific project's containers?

**Comment by zak-schlemmer** [comment]
`robot projects` also now outputs information on if the project is "built" and/or "running"
