### ISSUE TITLE
Multi-site, multi-url, same repo support

### ISSUE THREAD

**Issue by donaldwasserman** [zak-schlemmer/robot#24]
Whats the ability to use code directory A with multiple sites folders X, Y, Z?

Similar question for saying I want to use code directory A for url edge.robot and master.robot.

**Comment by zak-schlemmer** [comment]
The system in place at the moment is to use project_subproject for naming things in the docker-compose.yml file.
You will notice robot will not let you name a project with a _ for that reason.
That is how robot knows that multiple file systems or URL are in the same project and treats them accordingly.
This also might help explain why it is handled this way.
[example-integration-script](https://github.com/zak-schlemmer/robot/blob/master/template/example.integration.sh)
All and all though, you should find that if you want to connect things together from different projects (ie. different docker-compose.yml file) the fact that they all exist within the same network will give you the ability to connect anything together.
telnet, netstat, and other useful commands are built in automatically to allow you ability to test connection between containers.
`docker inspect <container_name>`
can also provide quite a bit of useful information about your containers

**Comment by zak-schlemmer** [comment]
To clarify, when I say:

> You will notice robot will not let you name a project with a _ for that reason.

I'm saying, if you were to run:
`robot create my_project`
It would stop you and ask you to use a . or - instead of _ for this reason.

**Comment by zak-schlemmer** [comment]
It would also really help if I were to add a template project that would follow this example.

**Comment by zak-schlemmer** [comment]
https://github.com/zak-schlemmer/robot/issues/43 was created to add a template example of this.
Keeping this open until the things discussed are added to the documentation.

**Comment by zak-schlemmer** [comment]
Eh, I'll document more later.
