### ISSUE TITLE
Ability To Create Project from Arbitrary Directories

### ISSUE THREAD

**Issue by donaldwasserman** [zak-schlemmer/robot#45]
I want to be able to add project A from `~/personal/projectA` and project B `~/work/projectB`

**Comment by zak-schlemmer** [comment]
Would an acceptable solution be to have robot symlink the dir to robot.dev?
This way your files would exist wherever, and robot could still find it no matter where it was.
Would you want to do this on 'robot create'? or after-the-fact?

**Comment by donaldwasserman** [comment]
I think we talked about this later, but this is what i'm thinking: 

`robot create .` or `robot create ~/path/to/my/dir`

I really see only a limited use case for after-the-fact pointing, unless its easier to do than creating from scratch.

**Comment by zak-schlemmer** [comment]
I am exploring ideas for this now.
I've decided to work on this in the branch:
`dir-flag`

**Comment by zak-schlemmer** [comment]
I would estimate I'm about half done with this.

**Comment by zak-schlemmer** [comment]
once I do: sync and ngrok
all wrapper functionality will be working for this
the only remaining concern will be making the creation more fluid with a db import type option/prompt

**Comment by zak-schlemmer** [comment]
I found one flaw in the logic overhaul when using multiple web heads (aka: project_subproject)

**Comment by zak-schlemmer** [comment]
`pwd | grep -oE '[^/]+'`
seems like this could somehow fix line 50 of robot to get this

**Comment by zak-schlemmer** [comment]
This is all now in the master branch.
